### ISSUE TITLE
为了一个cdn装nginx有点太重了吧

### ISSUE THREAD

**Issue by qinshulei** [kamidox/local-cdn#1]
如题，是不是可以考虑轻量级的方案。比如python脚本，内置启动文件服务器逻辑。运行脚本就自动修改hosts和启动服务。这样可以做到0配置。

**Comment by kamidox** [comment]
正解。

太阳底下没有新鲜事。这个问题确实有更优雅的解决方案：配置host到360的CDN（useso）就行了。

**Comment by qinshulei** [comment]
十分感谢～

```
echo 'ajax.googleapis.com ajax.useso.com' >>/etc/hosts
```

堪称完美
